import type { MRSummary, FileDiff, Suggestion } from '../../shared/types'

interface ReportInput {
  mr: MRSummary
  files: FileDiff[]
  suggestions: Suggestion[]
  riskScore: number
  model: string
  provider: string
  rawResponse?: string
}

const SEVERITY_ORDER = ['critical', 'error', 'warning', 'info'] as const
const SEVERITY_EMOJI: Record<string, string> = {
  critical: '🟥',
  error: '🟧',
  warning: '🟨',
  info: '🟦'
}

export function buildMarkdownReport(input: ReportInput): string {
  const { mr, files, suggestions, riskScore, model, provider, rawResponse } = input
  const lines: string[] = []

  /* ── Header ── */
  lines.push(`# Code Review Report — ${mr.title}`)
  lines.push('')
  lines.push(`> Generated by CodeSense on ${new Date().toLocaleString()}`)
  lines.push('')

  /* ── MR details ── */
  lines.push('## Merge Request')
  lines.push('')
  lines.push('| | |')
  lines.push('|---|---|')
  lines.push(`| **MR** | [!${mr.iid} — ${mr.title}](${mr.webUrl}) |`)
  lines.push(`| **Author** | @${mr.author} |`)
  lines.push(`| **Branches** | \`${mr.sourceBranch}\` → \`${mr.targetBranch}\` |`)
  lines.push(`| **Created** | ${new Date(mr.createdAt).toLocaleString()} |`)
  lines.push(`| **Last updated** | ${new Date(mr.updatedAt).toLocaleString()} |`)
  lines.push(`| **Files changed** | ${files.length} |`)
  lines.push(`| **Reviewed by** | ${provider} / \`${model}\` |`)
  lines.push(`| **Risk score** | **${riskScore}/100** |`)
  lines.push('')

  if (mr.description?.trim()) {
    lines.push('### Description')
    lines.push('')
    lines.push(mr.description.trim())
    lines.push('')
  }

  /* ── Findings summary ── */
  lines.push('## Findings Summary')
  lines.push('')
  if (suggestions.length === 0) {
    lines.push('_No issues found._')
  } else {
    lines.push('| Severity | Count |')
    lines.push('|---|---|')
    for (const sev of SEVERITY_ORDER) {
      const count = suggestions.filter((s) => s.severity === sev).length
      if (count > 0) lines.push(`| ${SEVERITY_EMOJI[sev]} ${sev} | ${count} |`)
    }
    lines.push(`| **Total** | **${suggestions.length}** |`)
  }
  lines.push('')

  /* ── Per-file detail ── */
  lines.push('## Changes & Findings by File')
  lines.push('')

  for (const file of files) {
    const fileSuggestions = suggestions
      .filter((s) => s.filePath === file.newPath || s.filePath === file.oldPath)
      .sort((a, b) => a.line - b.line)

    const { added, removed } = countChanges(file.diff)
    const badges = [
      file.isNew ? '🆕 new' : '',
      file.isDeleted ? '🗑 deleted' : '',
      file.isRenamed ? `📝 renamed from \`${file.oldPath}\`` : ''
    ].filter(Boolean).join(' · ')

    lines.push(`### \`${file.newPath}\``)
    lines.push('')
    lines.push(`**+${added} / −${removed}**${badges ? ` · ${badges}` : ''} · ${fileSuggestions.length} finding${fileSuggestions.length === 1 ? '' : 's'}`)
    lines.push('')

    if (fileSuggestions.length > 0) {
      for (const s of fileSuggestions) {
        lines.push(`#### ${SEVERITY_EMOJI[s.severity] ?? ''} Line ${s.line} — ${s.title}`)
        lines.push('')
        lines.push(`*Severity: ${s.severity} · Source: ${s.source === 'ai' ? 'AI review' : 'Static analysis'}*`)
        lines.push('')
        lines.push(s.body)
        lines.push('')
      }
    }

    /* AI response objects for this file, verbatim */
    if (fileSuggestions.some((s) => s.source === 'ai')) {
      lines.push('<details>')
      lines.push('<summary>AI model response for this file</summary>')
      lines.push('')
      lines.push('```json')
      lines.push(
        JSON.stringify(
          fileSuggestions
            .filter((s) => s.source === 'ai')
            .map(({ filePath, line, severity, title, body }) => ({
              filePath, line, severity, title, body
            })),
          null,
          2
        )
      )
      lines.push('```')
      lines.push('')
      lines.push('</details>')
      lines.push('')
    }

    lines.push('<details>')
    lines.push('<summary>View diff</summary>')
    lines.push('')
    lines.push('```diff')
    lines.push(file.diff.trimEnd())
    lines.push('```')
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  /* ── Full raw model response ── */
  if (rawResponse?.trim()) {
    lines.push('## Full AI Model Response')
    lines.push('')
    lines.push(`*Verbatim output from ${provider} / \`${model}\`:*`)
    lines.push('')
    lines.push('<details>')
    lines.push('<summary>Show full response</summary>')
    lines.push('')
    lines.push('```')
    lines.push(rawResponse.trim().replace(/```/g, '\\`\\`\\`'))
    lines.push('```')
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  return lines.join('\n')
}

function countChanges(diff: string): { added: number; removed: number } {
  let added = 0
  let removed = 0
  for (const line of diff.split('\n')) {
    if (line.startsWith('+') && !line.startsWith('+++')) added++
    if (line.startsWith('-') && !line.startsWith('---')) removed++
  }
  return { added, removed }
}
